# -*- coding: utf-8 -*-
"""primer_programa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LlCtypd9iK9bfXBXWqf3277T1u1I4lmT

**Clase 04 de mayo - Ciclos (FOR)**
"""

n= int(input())
suma=0
for i in range (1,n+1):
    suma+=i
print(suma)

#Numeros impares 1 al 999
''' for numero in range(1, 1000, 2):
  print(numero) '''

#Numeros impares 1 al 999
numero_usuario=int(input("digite n: "))
for numero_par in range(0, numero_usuario + 1, 2):
  print(numero_par)

# de 1 al 100 con su respectivo cuadrado
for numero in range(1,101):
  print(numero,numero**2)

#Funcion range()
a=range(6) #[0,1,2,3,4,5]
#print(a)

b=range(6,11) #[6,7,8,9,10]
#print(b)

c=range(6,13,2) #[6,8,10.12]

for elemento in c:
  print(elemento, end=",")

#Imprimir lista de frutas>
lista_frutas=["lulo", "maracuya", "guanabana"]

for fruta in lista_frutas:
  print(fruta, end=" ")
  if(fruta=="lulo"):
    break

#Ejemplo for
lista_nombres=["Daniel", "Maria", "Lina"]
palabra="hola mundo"
palabra_2="mnu"
contador=0
contador_2=0

for elemento in palabra:
  for elemento_2 in palabra_2:
    if(elemento == elemento_2):
      print("letra está dentro de palabra", elemento)
  
    print("elemento for externo ", elemento)
    print("elemento_2 for interno ", elemento_2)
    print("dentro for interno \n")

print("for principal")

"""**Clase 03 de mayo - Ciclos**"""

#For en python
lista_nombres=["Daniel", "Maria", "Lina"]
palabra="hola mundo"

print(palabra[5])

''' print(lista_nombres[0])
print(lista_nombres[1])
print(lista_nombres[2]) '''

#Ejercicios cuadrado de numeros del 1 al 100:
numero=1
while(numero <= 100):
  #print(numero**2)
  numero=numero+1 #=> numero+=1

numero_impar = 1
numero_par = 2
while (numero_impar < 1000) or (numero_par < 1000):
  if (numero_impar%2 != 0) or (numero_par%2 == 0 <1000):
    print(numero_impar, numero_par)
  numero_par +=1
  numero_impar+=1

#Ejercicio numeros pares y numeros impares del 1 al 1000:
print("lista pares")
numero_par=2
while(numero_par <=1000):#Es par
  print(numero_par)
  numero_par+=2
  
print("lista impares")
numero_impar=1
while(numero_impar <=999):#Es par
  print(numero_impar)
  numero_impar+=2

''' numero = int(input("ingrese un  numero: "))
while(numero != 0):
  print(numero)
  numero = int(input("ingrese un  numero: ")) '''

''' numero=int(input("ingrese número entero "))
while(numero!=0):
  print(numero)
  numero=int(input("ingrese número entero ")) '''

numero_entero = int(input("Ingrese un valor entero "))
while(numero_entero != 0):
  print(numero_entero)
  numero_entero = int(input("Ingrese un valor entero "))
  if(numero_entero == 0):
    print("Finalizo")

#Trabajo en Casa
i=0
entrar=True
while ((i>=65 and i<=122) or entrar):
  entrar=False
  a=chr(i)
  print(a)
  i=int(input("ingrese su numero "))

num_entero = int(input("ingrese su numero"))
while(num_entero<65 or num_entero>90):
  num_entero = int(input("ingrese su numero de nuevo"))
print("Finalizo While")

#Ciclos while
''' print("algo previo")
i=1
while(i<=6):
  print(i)
  i+=1
print("i= ",i)
print("finalizó while") '''


#i, j
''' i=2
j=25
while(i<j):
  print(i, j, sep=", ")
  i*=2
  j+=10
print("finalizó")
print(i, j, sep=", ")
 '''


#numero más pequeño mayor que cero
def min_maquina():
  Xo = 1.0
  Xi = Xo / 2.0
  while Xi > 0.0:
    Xo = Xi
    Xi = Xo / 2.0
  return Xo

retorno_funcion=min_maquina()
print(retorno_funcion)

"""Clase 02 de mayo de 2022 **Condicionales anidados**"""

color=input("Escriba el color: ")
if(color=="verde"):
  print("el color es verde")
elif(color=="amarillo"):
  print("el color es amarillo")
elif(color=="gris"):
  print("es color es gris")
elif(color=="rojo"):
  print("es color es rojo")
elif(color=="azul"):
  print("es color es azul")
else:
  print("color diferente al esperado")
print("finalizó")

"""Clase 28 de abril de 2022 **Funciones 2 parámetros y condicionales**

"""

#Ejercicio similar RETO 1
#entrada edad de una persona
#imprimir= edad edad**2 edad*4
##edad*4 >50 => "viejo"
##edad*4 >40 pero menor que 50 => "adulto"
##edad*4 > 0 pero menor que 40 => "joven"

edad = int(input())
edad_cuadrada=edad ** 2
edad_4 = edad*4
categoria=""

if(edad_4 >= 0 and edad_4 < 40 ):
  categoria="joven"
elif(edad_4 >= 40 and edad_4 < 50):
  categoria="adulto"
else:
  categoria="viejo"

print(str(edad)+" "+str(edad_cuadrada)+ " "+str(edad_4))
print(categoria)

#Condicionales:
a=5
b=6
c=8
d=7
def calcular_numero_mayor(a,b):
  if(a!=b or c>=d and b==d):
    print("verdadero")
  else:
    print("falso")


if(a>10):
  print("la variable es: ",a)
if(b>5):

#Area rectángulo

base=int(input())
altura=int(input())

def calcular_area_rectangulo(base_parametro, altura_parametro):
  area=base_parametro*altura_parametro
  return area
print("el resultado es: ", calcular_area_rectangulo(base, altura))

#Mostrar nombre y edad:

nombre_arg=input()
edad_arg=int(input())

def mostrar_datos(nombre, edad):
  respuesta=nombre+" "+str(edad)
  return respuesta

print(mostrar_datos(nombre_arg, edad_arg))

def sumados_numeros(numero_1, numero_2):
  suma = numero_1 + numero_2
  cuadrado = suma ** 2
  return cuadrado

print("Por favor digite primer número")
numero_1_usuario=int(input())
print("Por favor digite segundo número")
numero_2_usuario=int(input())

print("El retorno de los cuadrados sumados es: " + str(sumados_numeros(numero_1_usuario, numero_2_usuario)))


def elevar_cuadrado(suma):
  resultado = suma ** 2
  return resultado

numero_1_usuario=int(input())
numero_2_usuario=int(input())
suma_op=numero_1_usuario+numero_2_usuario
print(elevar_cuadrado(suma_op))

"""Clase 27 de abril de 2022 **Funciones**"""

def sumarle_1(numero):
  numero_resultado=numero+1
  return numero_resultado

def calcular_cuadrado(x):
  cuadrado=x**2
  return cuadrado

def saludar(nombre):
  saludo = "Hola "+nombre
  return saludo

#resultado_funcion=sumarle_1(5)
print(sumarle_1(5))
variable_entrada=6
nombre_persona="Daniel"
print(calcular_cuadrado(variable_entrada))
print(saludar(nombre_persona))


#Area circulo
import math
def area_circulo(r):
  area = math.pi * r ** 2
  return area
print(area_circulo(2))


a=5
a=5/2
print(a)

"""Clase 26 de abril de 2022 **Tipos de datos parte 2**"""

m1=10
m2=5
r=7
G=6.67384E-11
F = G*((m1*m2)/(r**2))
#print(F)


#Operadores lógicos
x=True
y=not x
print(x)
x=not y
x=y
print(x)
#Exp. log AND
a=False
b=False
if(a and b):
  sdkjksdj


#Exp. log OR
a=False
b=False
if(a or b):
  sdkjksdj


#Igualdad
a=True
A=False
i=5
j=5
k="Hola"
l="hola"
if(k == l):
  sdkjksdj


#diferente
a=True
A=False
i=5
j=5
k="Hola"
l="hola"
if(k != l):
  sdkjksdj

#Prioridad operadores
a= -(42) // 6 + 7 * 3 - 39
#7 + 21 - 39
#28-39
#-11
print(a)

"""Clase 25 de abril de 2022
**Tipos de datos**
"""

#Variables enteras:
i=0
variable_principal=10
j=-8
print(i)

#Variables reales:
k=1.8
gravedad=9.8
l=-0.21457
print(gravedad)

#Variables booleanas
es_mayor=True
es_igual=False
a=True
print(es_mayor)

#Variables caracteres:
caracter1="a"
caracter2='a'
caracter_3="%"
print(caracter_3)

#Variables string (texto):
string_1="hola mundo"
string_2="mi primer string"
str_3="soy un string pequeño pero ....."
print(str_3)

"""Clase 25 de abril de 2022
**Op. asignación**
"""

KAPPA: float = 9E+9
def ley_coulomb(Q1, Q2, r):
  modulo = KAPPA * Q1 * Q2 / r ** 2
  return modulo
carga1 = float(input("Carga 1: "))
carga2 = float(input("Carga 2: "))
distancia = float(input("Distancia entre cargas: "))
print("El modulo de la fuerza es:", end = " ")
print(ley_coulomb(carga1, carga2, distancia))









from IPython.display import YouTubeVideo

YouTubeVideo("6iOlB0QLy84")

import random # se importa la librería de python random


j:int=10
sujetos = ["bebé", " princess","mami"] #se define una lista
intenciones =["yo quiero","yo puedo","yo vengo a","voy a"]
verbos = ["encendelte","amalte","ligal","jugal"]
advs =["suave","lento","lápido","fuelte"]
complementos_uno = ["hasta que salga el sol","toda la noche", 
                     "hasta el amanecer","todo el día"]
complementos_dos = ["sin anestesia","sin compromiso",
                     "feis to feis", "sin miedo"]


sujeto_seleccionado = random.choice(sujetos) 
#se utiliza la librería para seleccionar un elemento al azar de la lista sujetos
intencion_seleccionada = random.choice(intenciones) 
verbo_seleccionado = random.choice(verbos)
adv_seleccionado=random.choice(advs)
compl1s_seleccionado = random.choice(complementos_uno)
compl2s_seleccionado = random.choice(complementos_dos)

print(j)

print("letra generada: "+ sujeto_seleccionado + " "
+ intencion_seleccionada + " " + verbo_seleccionado + " "
+ adv_seleccionado + " "+ compl1s_seleccionado + " "
+ compl2s_seleccionado) # se imprime la canción

#Hola grupo 36

print("Variable 1:")
variable_1 = int(input())

print("Variable 2:")
variable_2 = int(input())

variable_3 = variable_1 + variable_2

print("El resultado de la suma es: ")
print(variable_3)