# -*- coding: utf-8 -*-
"""utilsvideo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BWnlPIG0nlcRIAy8TGAy24lZQHpmaGPD
"""

def peliculas_sin_repeticion(E1):
  lista_1=[]
  for numero in E1:
      if numero not in lista_1:
        lista_1.append(numero)
  return lista_1

def pelicula_en_posiciones(E1,E2,E3):
  lista_definitiva = []
  for dato in E1:
    if E2[dato] == E3:
      lista_definitiva.append(dato)
  return lista_definitiva

def solo_drama(E1,E2):
  lista_solo_drama=[]
  for pelicula in E1:
      if pelicula not in E2:
         lista_solo_drama.append(pelicula)
  return lista_solo_drama

def numero_cambios(p1,p2):
    contador = 0
    contador2 = 0
    resultado = 0

    for peli in p2:
      if peli not in p1:
        contador+=1
    for peli in p1:
      if peli not in p2:
        contador2+=1

    if contador < contador2:
      resultado = contador
      return resultado

    if contador > contador2:
      resultado = contador2
      return resultado

    if contador == contador2:
      resultado = contador
      return resultado