# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mncJaSu69068DDLUF8wQ7JBcNA9mJv4E
"""

tupla = input()
tupla=tupla.upper()
tupla=tupla.replace(",","")

paquetes=[]
contador=[0]
paquetes.append(tupla[0])

for caracter in tupla:
        if caracter != paquetes[-1]:
          paquetes.append(caracter)
          contador.append(1)
        else:
          contador[-1]+=1

def quitar_repetidos(dato):
    nuevo_caracter = ""
    caracter_anterior = ""
    for caracter in dato:
        if len(nuevo_caracter) == 0:
            nuevo_caracter += caracter
            caracter_anterior = caracter
        if caracter == caracter_anterior:
            continue
        else:
            nuevo_caracter += caracter
            caracter_anterior = caracter
    return nuevo_caracter


print(*contador)
print(' '.join(quitar_repetidos(tupla)))