# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K8Ud1z8epp3SZi0zBIltCCUvPWKEmLM-
"""

paq_datos=("R,R,R,Y,Y,Y,Y,W,W,W,C,C,O,y,Y,Y,Y,C,C,X,X,X,S,S,S,S")
paq_datos=paq_datos.upper()
lista=paq_datos.split(",")
x=lista[0]
acumulado=1
lista_1=[] #para datos resumidos
lista_2=[] #contador
for indice in range(1,len(lista)):
  if lista [indice] == x:
    acumulado+=1
  else:
    lista_1.append(x)
    lista_2.append(acumulado)
    x=lista[indice]
    acumulado=1
lista_1.append(x)
lista_2.append(acumulado) 
print(*lista_1)
print(*lista_2)