# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bjL5pJRV9RYua1VJ0XI1QLUZw7h2FquQ
"""

j67 = int(input())
m15 = (j67 * 2 + 4)
r99 = (j67 + m15) / 5

print (j67, "    ",j67, m15, int(r99))

if r99 >= 0 and r99 < 21: print("uno")

if r99 >= 21 and r99 < 41: print("dos")

if r99 >= 41 and r99 < 81: print("tres")

if r99 >= 81: print("cuatro")